package:
  name: starfish_package
  version: "1.0.0"  # Change this to your desired version

source:
  git_url: https://github.com/egluckthaler/starfish.git
  git_rev: main

build: 
  scripts:
    - exe/starfish

requirements:
  build:
    - python >=3.6,<3.12
    - numpy >=1.22
  run:
    - python >=3.6,<3.12  # Add your runtime dependencies here
    - numpy >=1.22
    - mummer4=4.0.0
    - bedtools=2.30.0
    - sourmash>=4.6
    - blast=2.12.0
    - mcl=14.137
    - circos=0.69.8
    - minimap2=2.24
    - hmmer=3.3.2
    - metaeuk=6.a5d39d9
    - mafft=7.508
    - mmseqs2=14.7e284
    - samtools=1.6
    - eggnog-mapper=2.1.12

test:
  commands:
    - "starfish insert -h"

about:
  home: "https://github.com/egluckthaler/starfish"
  license: "AGPL-3.0-or-later"  # Your project's license
  summary: "a modular toolkit for giant mobile element annotation"
